# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Generate Filtered CIDR Metadata file

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 22 * * *'    # At every 15th minute

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    
    - name: Install Dependancies
      run: npm install
    
    - name: Execute Metadata filter script
      id: filter_data
      run: |
        BLOCKS=node ./index.js
        echo "::set-output name=BLOCKS::$BLOCKS"
    
    - name: Overwrite file
      uses: "DamianReeves/write-file-action@master"
      with:
          path: outputs/filtered_metadata.txt
          write-mode: overwrite
          contents: |
            ${{join(steps.filter_data.outputs.BLOCKS, '\n')}}
            
    - name: Commit & Push
      uses: Andro999b/push@v1.3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
          message: 'Overwritten by Github Actions'
    
    
